<?php
declare(strict_types=1);
$root=dirname(__DIR__);require $root.'/app/bootstrap.php';$failures=0;
$test=function(string $name,callable $case)use(&$failures):void{try{$case();echo "PASS $name\n";}catch(Throwable $e){$failures++;echo "FAIL $name: {$e->getMessage()}\n";}};
$test('UUID format',function(){if(!preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/',Catch\Core\Id::uuid()))throw new RuntimeException('Invalid UUID');});
$test('Capture validation requires content',function(){$errors=(new Catch\Validation\CaptureValidator())->validate(['client_capture_id'=>'test','type'=>'text']);if(!isset($errors['content']))throw new RuntimeException('Content accepted');});
$test('Capture validation accepts text',function(){$errors=(new Catch\Validation\CaptureValidator())->validate(['client_capture_id'=>'test','type'=>'text','text'=>'Hello']);if($errors)throw new RuntimeException(json_encode($errors));});
$test('Prerelease access permits only the configured Sorkos user',function()use($root){$directory=sys_get_temp_dir().'/catch-access-'.bin2hex(random_bytes(6));mkdir($directory.'/config',0777,true);file_put_contents($directory.'/config/config.ini',"[access]\nprerelease=true\nallowed_sorkos_user_id=usr_allowed\n");$policy=new Catch\Core\AccessPolicy(Catch\Core\Config::load($directory));if(!$policy->allowsSorkosUserId('usr_allowed')||$policy->allowsSorkosUserId('usr_other')||$policy->allowsSorkosUserId(''))throw new RuntimeException('Prerelease allowlist failed');unlink($directory.'/config/config.ini');rmdir($directory.'/config');rmdir($directory);});
$test('Released access does not require an allowlist',function()use($root){$directory=sys_get_temp_dir().'/catch-access-'.bin2hex(random_bytes(6));mkdir($directory.'/config',0777,true);file_put_contents($directory.'/config/config.ini',"[access]\nprerelease=false\n");$policy=new Catch\Core\AccessPolicy(Catch\Core\Config::load($directory));if(!$policy->allowsSorkosUserId('usr_any'))throw new RuntimeException('Released access was denied');unlink($directory.'/config/config.ini');rmdir($directory.'/config');rmdir($directory);});
$test('Auth exchange is compatible with PHP 8.5',function()use($root){$source=(string)file_get_contents($root.'/app/Services/AuthService.php');if(str_contains($source,'curl_'.'close('))throw new RuntimeException('Deprecated cURL close call found');});
$test('Shortcut responses always expose flat strings',function(){$empty=Catch\Http\Response::shortcutPayload();$success=Catch\Http\Response::shortcutPayload('', 'capture-id');$failure=Catch\Http\Response::shortcutPayload('Failed.', '');foreach([$empty,$success,$failure] as $payload){if(array_keys($payload)!==['error','result']||!is_string($payload['error'])||!is_string($payload['result']))throw new RuntimeException('Invalid shortcut response envelope');}});
$test('OpenAPI documents every public machine route',function()use($root){$source=(string)file_get_contents($root.'/app/Core/Application.php');preg_match_all("/\\\$f3->route\\('([A-Z]+) ([^']+)'/",$source,$matches,PREG_SET_ORDER);$routes=[];foreach($matches as $match){if($match[2]!=='/health'&&!str_starts_with($match[2],'/api/'))continue;$path=preg_replace('/@([A-Za-z_][A-Za-z0-9_]*)/','{$1}',$match[2]);$routes[]=$match[1].' '.$path;}$spec=json_decode((string)file_get_contents($root.'/public/docs/api/openapi.json'),true,512,JSON_THROW_ON_ERROR);$documented=[];foreach($spec['paths'] as $path=>$methods)foreach($methods as $method=>$operation)if(in_array($method,['get','post','put','patch','delete'],true))$documented[]=strtoupper($method).' '.$path;sort($routes);sort($documented);if($routes!==$documented)throw new RuntimeException('OpenAPI route inventory differs from Application routes: '.json_encode(['routes'=>$routes,'documented'=>$documented]));});
$test('Swagger UI is fully local',function()use($root){$index=(string)file_get_contents($root.'/public/docs/api/index.html');foreach(['swagger-ui.css','swagger-ui-bundle.js','swagger-ui-standalone-preset.js','LICENSE'] as $asset)if(!is_file($root.'/public/vendor/swagger-ui/'.$asset))throw new RuntimeException('Missing Swagger UI vendor asset: '.$asset);if(!str_contains($index,'/vendor/swagger-ui/')||preg_match('/(?:src|href)=["\']https?:/i',$index))throw new RuntimeException('Swagger UI has an external runtime dependency');});
exit($failures?1:0);
