<a class="back-link" href="/devices">← Alle Geräte</a>
<header class="device-detail-heading"><div><span class="connection-status connection-status-<?=htmlspecialchars($device['status'])?>"><span aria-hidden="true"></span><?=$device['status']==='connected'?'Verbunden':'Einrichtung offen'?></span><h1><?=htmlspecialchars($device['name'])?></h1><p><?=htmlspecialchars($device['platform']==='ipados'?'iPadOS':'iOS')?> · Mobil</p></div><form method="post" action="<?=htmlspecialchars($deviceUrl)?>/delete"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-danger" type="submit">Gerät entfernen</button></form></header>

<?php if($device['status']==='setup'): ?>
<section class="pairing-flow" data-device-status-url="<?=htmlspecialchars($deviceUrl)?>/status" data-polling="<?=isset($device['pairing_code'])?'true':'false'?>">
  <ol class="pairing-steps">
    <li class="pairing-step pairing-step-active"><span>1</span><div><h2>Setup-Kurzbefehl laden</h2><p>Öffne die Datei auf deinem iPhone oder iPad. Der Kurzbefehl richtet die sichere Verbindung zu Catch ein.</p><a class="button button-primary" href="<?=htmlspecialchars($shortcutUrl)?>" download>Catch Setup herunterladen</a></div><div class="shortcut-qr"><div data-qr-code data-qr-value="<?=htmlspecialchars($shortcutUrl)?>" aria-label="QR-Code zum Shortcut-Download"></div><small>Mit der Kamera des Geräts scannen</small></div></li>
    <li class="pairing-step <?=isset($device['pairing_code'])?'pairing-step-active':''?>"><span>2</span><div><h2>Verbindungscode eingeben</h2><?php if(isset($device['pairing_code'])):?><p>Trage diesen Code ein, wenn der Setup-Kurzbefehl danach fragt.</p><div class="pairing-code-row" data-copy-row><code data-copy-source><?=htmlspecialchars($device['pairing_code'])?></code><button class="button button-secondary" type="button" data-copy-button>Code kopieren</button></div><?php else:?><p>Erzeuge den Code erst, wenn du den Setup-Kurzbefehl auf diesem Gerät geöffnet hast.</p><form method="post" action="<?=htmlspecialchars($deviceUrl)?>/pairing-code"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-secondary" type="submit">Verbindungscode erzeugen</button></form><?php endif;?></div></li>
    <li class="pairing-step <?=isset($device['pairing_code'])?'pairing-step-waiting':''?>"><span>3</span><div><h2>Auf Verbindung warten</h2><p data-pairing-status><?=isset($device['pairing_code'])?'Diese Seite prüft automatisch, ob das Gerät verbunden wurde.':'Nach dem Erzeugen des Codes wartet Catch auf den ersten Kontakt.'?></p><?php if(isset($device['pairing_code'])):?><div class="waiting-indicator" role="status"><span aria-hidden="true"></span>Prüfung läuft alle 7 Sekunden</div><?php endif;?></div></li>
  </ol>
</section>
<?php else: ?>
<section class="connected-summary"><div class="connected-check" aria-hidden="true">✓</div><div><h2>Dieses Gerät ist verbunden</h2><p>Der Setup-Kurzbefehl hat ein Gerätetoken erhalten. Pairing-Code und Einrichtungsdaten wurden gelöscht.</p><dl><div><dt>Verbunden seit</dt><dd><?=htmlspecialchars(date('d.m.Y, H:i',strtotime($device['connected_at'])))?></dd></div><?php if($device['last_seen_at']):?><div><dt>Letzter Kontakt</dt><dd><?=htmlspecialchars(date('d.m.Y, H:i',strtotime($device['last_seen_at'])))?></dd></div><?php endif;?></dl></div></section>
<section class="available-shortcuts"><div class="section-heading"><div><h2>Kurzbefehle für dieses Gerät</h2><p>Alle Kurzbefehle verwenden das vom Setup gespeicherte Gerätetoken.</p></div></div><div class="shortcut-list"><article><div><strong>Catch teilen</strong><p>Text, Links, Bilder und Dateien aus dem Share Sheet erfassen.</p></div><span class="badge">Folgt</span></article><article><div><strong>Catch Sprachaufnahme</strong><p>Gedanken diktieren und direkt an die Inbox senden.</p></div><span class="badge">Folgt</span></article></div></section>
<?php endif; ?>

<?php if($device['status']==='setup'): ?><script src="/assets/vendor/qrcode.js"></script><?php endif; ?>
