<a class="back-link" href="/devices">← All devices</a>
<header class="device-detail-heading"><div><span class="connection-status connection-status-<?=htmlspecialchars($device['status'])?>"><span aria-hidden="true"></span><?=$device['status']==='connected'?'Connected':'Setup pending'?></span><h1><?=htmlspecialchars($device['name'])?></h1><p><?=htmlspecialchars($device['platform']==='ipados'?'iPadOS':'iOS')?> · Mobile</p></div><form method="post" action="<?=htmlspecialchars($deviceUrl)?>/delete" onsubmit="return confirm('Remove this device and revoke its access?')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-danger" type="submit">Remove device</button></form></header>

<?php if($device['status']==='setup'): ?>
<section class="pairing-flow" data-device-status-url="<?=htmlspecialchars($deviceUrl)?>/status" data-polling="<?=isset($device['pairing_code'])?'true':'false'?>">
  <ol class="pairing-steps">
    <li class="pairing-step pairing-step-active"><span>1</span><div><h2>Download the setup shortcut</h2><p>Open the file on your iPhone or iPad. The shortcut creates a secure connection to Catch.</p><a class="button button-primary" href="<?=htmlspecialchars($shortcutUrl)?>" download>Download Catch Setup</a></div><div class="shortcut-qr"><div data-qr-code data-qr-value="<?=htmlspecialchars($shortcutUrl)?>" aria-label="QR code for the shortcut download"></div><small>Scan with your device camera</small></div></li>
    <li class="pairing-step <?=isset($device['pairing_code'])?'pairing-step-active':''?>"><span>2</span><div><h2>Enter the pairing code</h2><?php if(isset($device['pairing_code'])):?><p>Enter this code when the setup shortcut asks for it.</p><div class="pairing-code-row" data-copy-row><code data-copy-source><?=htmlspecialchars($device['pairing_code'])?></code><button class="button button-secondary" type="button" data-copy-button>Copy code</button></div><?php else:?><p>Create the code only after opening the setup shortcut on this device.</p><form method="post" action="<?=htmlspecialchars($deviceUrl)?>/pairing-code"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-secondary" type="submit">Create pairing code</button></form><?php endif;?></div></li>
    <li class="pairing-step <?=isset($device['pairing_code'])?'pairing-step-waiting':''?>"><span>3</span><div><h2>Wait for the connection</h2><p data-pairing-status><?=isset($device['pairing_code'])?'This page automatically checks whether the device is connected.':'After creating the code, Catch waits for the first connection.'?></p><?php if(isset($device['pairing_code'])):?><div class="waiting-indicator" role="status"><span aria-hidden="true"></span>Checking every 7 seconds</div><?php endif;?></div></li>
  </ol>
</section>
<?php else: ?>
<section class="connected-summary"><div class="connected-check" aria-hidden="true">✓</div><div><h2>This device is connected</h2><p>The setup shortcut received a device token. The pairing code and temporary setup data have been deleted.</p><dl><div><dt>Connected</dt><dd><?=htmlspecialchars(date('M j, Y, H:i',strtotime($device['connected_at'])))?></dd></div><?php if($device['last_seen_at']):?><div><dt>Last seen</dt><dd><?=htmlspecialchars(date('M j, Y, H:i',strtotime($device['last_seen_at'])))?></dd></div><?php endif;?></dl></div></section>
<section class="available-shortcuts"><div class="section-heading"><div><h2>Shortcuts for this device</h2><p>Every shortcut uses the device token saved during setup.</p></div></div><div class="shortcut-list"><article><div><strong>Share to Catch</strong><p>Capture text, links, images, and files from the Share Sheet.</p></div><span class="badge">Coming soon</span></article><article><div><strong>Catch Voice</strong><p>Record a thought and send it straight to your inbox.</p></div><span class="badge">Coming soon</span></article></div></section>
<?php endif; ?>

<?php if($device['status']==='setup'): ?><script src="/assets/vendor/qrcode.js"></script><?php endif; ?>
