<section class="capture-list" aria-label="Captures" data-capture-list>
<?php if (!$captures): ?><div class="empty-state"><div class="empty-glyph">C</div><h2><?=$status === 'trash' ? 'Trash is empty' : 'Nothing here yet'?></h2><p><?=$status === 'trash' ? 'Captures you move to Trash will appear here for 30 days.' : 'Captures matching this view will appear here.'?></p></div><?php endif; ?>
<?php foreach ($captures as $capture): $icon = match($capture['type']) {
    'url' => 'link','image' => 'image','audio' => 'voice',default => 'text'
}; ?>
<article class="capture-row">
  <?php if (!empty($bulkFormId)): ?><input class="capture-select" type="checkbox" name="capture_ids[]" value="<?=htmlspecialchars($capture['id'])?>" form="<?=htmlspecialchars($bulkFormId)?>" aria-label="Select capture #<?=(int)$capture['catch_number']?>"><?php endif; ?>
  <span class="type-icon" aria-hidden="true"><i class="glyph glyph-<?=htmlspecialchars($icon)?>"></i></span>
  <div class="capture-copy"><a class="capture-title-link" href="/captures/<?=urlencode($capture['id'])?>"><strong><?=htmlspecialchars($capture['title'] ?: mb_strimwidth($capture['text'] ?: $capture['url'] ?: 'Attachment', 0, 90, '…'))?></strong></a><div class="capture-subline"><span class="capture-meta"><span class="capture-number">#<?=(int)$capture['catch_number']?></span><span aria-hidden="true"> · </span><?php $timeValue = $status === 'trash' ? $capture['deleted_at'] : $capture['created_at']; ?><time datetime="<?=htmlspecialchars(str_replace(' ', 'T', substr($timeValue, 0, 19)) . 'Z')?>" data-local-time data-date-style="medium" data-time-style="short">UTC <?=htmlspecialchars($timeValue)?></time><?=$status === 'trash' ? ' · in Trash' : ''?></span><?php if (!empty($capture['tags'])): ?><span class="capture-row-tags"><?php foreach ($capture['tags'] as $tag): ?><a class="tag-link" href="<?=htmlspecialchars($tag['url'])?>"><?=htmlspecialchars($tag['name'])?></a><?php endforeach; ?></span><?php endif; ?></div></div>
  <?php if ($status === 'trash'): ?><form method="post" action="/captures/<?=urlencode($capture['id'])?>/restore"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-quiet" type="submit">Restore</button></form><?php else: ?><form method="post" action="/captures/<?=urlencode($capture['id'])?>/<?=$status === 'archived' ? 'delete' : 'archive'?>"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="icon-button <?=$status === 'archived' ? 'button-danger-outline' : ''?>" type="submit" aria-label="<?=$status === 'archived' ? 'Move to Trash' : 'Archive'?>"><i class="glyph glyph-<?=$status === 'archived' ? 'trash' : 'archive'?>" aria-hidden="true"></i></button></form><?php endif; ?>
</article>
<?php endforeach; ?>
</section>
