<a class="back-link" href="/inbox">← Back to inbox</a>
<article class="detail">
  <header><span class="type-label">Catch #<?=(int)$capture['catch_number']?> &middot; <?=htmlspecialchars($capture['type'])?></span><h1><?=htmlspecialchars($capture['title']?:'Capture')?></h1><p><?=htmlspecialchars((new DateTime($capture['created_at']))->format('M j, Y, H:i'))?> · <?=htmlspecialchars($capture['source'])?></p></header>
  <?php if($capture['text']): ?><section><h2>Content</h2><div class="prose"><?=nl2br(htmlspecialchars($capture['text']))?></div></section><?php endif; ?>
  <?php if($capture['url']): ?><section><h2>Link</h2><a class="url-card" href="<?=htmlspecialchars($capture['url'])?>" target="_blank" rel="noopener noreferrer"><?=htmlspecialchars($capture['url'])?><span>↗</span></a></section><?php endif; ?>
  <?php if($capture['extracted_text']): ?><details><summary>Extracted text</summary><div class="prose"><?=nl2br(htmlspecialchars($capture['extracted_text']))?></div></details><?php endif; ?>
  <?php if($capture['attachments']): ?><section><h2>Attachments</h2><div class="attachment-list"><?php foreach($capture['attachments'] as $attachment): ?><div><strong><?=htmlspecialchars($attachment['original_name'])?></strong><span><?=htmlspecialchars($attachment['mime_type'])?> · <?=number_format($attachment['size_bytes']/1024,1,'.',',')?> KB</span></div><?php endforeach;?></div></section><?php endif; ?>
  <footer class="detail-actions"><form method="post" action="/captures/<?=urlencode($capture['id'])?>/archive"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-secondary">Archive</button></form><form method="post" action="/captures/<?=urlencode($capture['id'])?>/delete" onsubmit="return confirm('Delete this capture?')"><input type="hidden" name="_csrf" value="<?=htmlspecialchars($csrf)?>"><button class="button button-danger">Delete</button></form></footer>
</article>
