CREATE TABLE IF NOT EXISTS catch_capture_debug_requests (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  device_id CHAR(36) NOT NULL,
  token_id CHAR(36) NOT NULL,
  token_scope VARCHAR(40) NOT NULL,
  endpoint VARCHAR(120) NOT NULL,
  method VARCHAR(10) NOT NULL,
  remote_ip VARCHAR(45) NULL,
  user_agent VARCHAR(500) NULL,
  content_type VARCHAR(160) NULL,
  content_length BIGINT UNSIGNED NULL,
  idempotency_key VARCHAR(255) NULL,
  parameters_json JSON NOT NULL,
  files_json JSON NULL,
  verdict VARCHAR(40) NOT NULL DEFAULT 'processing',
  http_status SMALLINT UNSIGNED NULL,
  capture_id CHAR(36) NULL,
  error_message TEXT NULL,
  created_at DATETIME(6) NOT NULL,
  completed_at DATETIME(6) NULL,
  INDEX idx_capture_debug_device_created (device_id, created_at),
  INDEX idx_capture_debug_user_created (user_id, created_at),
  CONSTRAINT fk_capture_debug_user FOREIGN KEY (user_id) REFERENCES catch_users(id) ON DELETE CASCADE,
  CONSTRAINT fk_capture_debug_device FOREIGN KEY (device_id) REFERENCES catch_devices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
